name: Node.js CI with Dashboard

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Step to check out the repository code
    - uses: actions/checkout@v2

    # Step to set up the specified Node.js version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # Step to install dependencies
    - name: Install dependencies
      run: npm install
      
    # Step to install localtunnel for exposing the dashboard
    - name: Install localtunnel
      run: npm install -g localtunnel

    # Step to run the dashboard server
    - name: Start the dashboard server
      env:
        PORT: 8080
        LT_SUBDOMAIN: ${{ secrets.LT_SUBDOMAIN || 'cyber-bot-dashboard' }}
        AUTH_USERNAME: ${{ secrets.AUTH_USERNAME || 'admin' }}
        AUTH_PASSWORD: ${{ secrets.AUTH_PASSWORD || 'cyberbot' }}
      run: node server.js &
      
    # Step to run the bot with the correct port
    - name: Start the bot
      env:
        PORT: 8080
      run: npm start
